### ISSUE TITLE
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/hubot-docomo-dialogue

### ISSUE THREAD

**Issue by nkoyama** [bouzuya/hubot-docomo-dialogue#3]
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/hubot-docomo-dialogue
npm ERR! 404
npm ERR! 404 'hubot-docomo-dialogue' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
このように出るのですが、対応策はありますでしょうか。

**Comment by bouzuya** [comment]
hubot-docomo-dialogue は npm に登録されていません。

`$ npm i bouzuya/hubot-docomo-dialogue` などと実行し、 GitHub から取得してください。

**Comment by nkoyama** [comment]
ありがとうございます。
